### ISSUE TITLE
Received empty emails as welcome emails 

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#12]
When I created a user for the 2nd time, I received an almost empty emails : 

http://screencast.com/t/Nzg0MzUwZTA

**Comment by stanguy** [comment]
Works for me.

The line starting with "Bonjour" is part of the full message block, so there's no reason the message remainder would not be sent. Isn't it just gmail quote handling at work? Or is there really no text below the "Bonjour" line ?

**Comment by ssacard** [comment]
OK, I cannot reproduce the bug. Closing the issue.
