### ISSUE TITLE
Impossible to refuse to lend a DVD

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#19]
http://www.mondvdclub.fr/dvds/refuse/3

This feature seems to not have been implemented.

**Comment by stanguy** [comment]
works for me (maybe a side effect of a pending patch?)

**Comment by ssacard** [comment]
Login as admin (admin@dvdclub.com / password) 

=> http://screencast.com/t/MGUzZmUyZj

**Comment by sgruhier** [comment]
J'ai fait un test avec un nouveau user et cela fonctionne. Je pense que http://www.mondvdclub.fr/dvds/refuse/3 (le DVD id 3) n'existe plus dans la base, p-e suite a un reset

**Comment by ssacard** [comment]
OK, checked on Heroku.
