### ISSUE TITLE
The code is not protected against user who leave a club

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#22]
Scenario : 
- user 1 requests a DVD to user 2
  => The request is displayed in user 2 dashboard
- user 1 leaves the club
- user 2 reloads the page, but the DVD request of user 1 is still visible ! 

Problem : when user 2 clicks on refuse or accept, we get a server error 

http://screencast.com/t/MTRlOTQxNjUt

**Comment by stanguy** [comment]
What should happen when a user leaves a club and has a dvd from some other people through this club (or people from this club have one of his dvd) ?
Should those be silently discarded or should we keep them in the interface to handle the return?

**Comment by ssacard** [comment]
For this first version, silently discard them please. Later, we"ll handle a status where the user has "left" the club and we"ll find a proper status for the pending requests and ownerships.

**Comment by ssacard** [comment]
Impossible to test, as there is a server exception when I try to leave a club, the url is strange : http://www.mondvdclub.fr/user_dvd_clubs/2, it should be something more explicit lile "/leave_club/2

Exception : http://getexl.com/37w5i

**Comment by stanguy** [comment]
there was a small ruby version issue that I just fixed

**Comment by ssacard** [comment]
OK, vérifié.
