### ISSUE TITLE
Pouvoir écrire des pages de contenu

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#29]
J'ai besoin d'écrire des pages de contenu, notamment pour les pages du pied de page (about, legal, etc.) - quelle serait la solution la plus simple ?

**Comment by oelmekki** [comment]
Hello,

Alors, le plus simple serait bien sûr de les écrire en html. Je peux faire un controller pour rendre des pages statiques, si tu veux, ça te permettra de rajouter une page en écrivant un fichier apps/views/static/<ta_page>.html.erb

Après, si tu dois écrire beaucoup de pages ou en écrire souvent, on peut faire une page d'admin pour créer des articles.
- avantage : tu as un wysiwyg à disposition pour éditer du contenu
- inconvenient : il s'agit de contenu, et non plus d'une partie de l'app. C'est dans la base de donnée et ça n'est pas distribué aux autres installations de l'app.

Comme bonne pratique, je dirais que si la page fait partie intégrante de l'app (about et legal en sont de bons exemples), on les écrit en html, et si s'agit de contenu plus "subsidiaire" (article de blog, page d'annoucement), on en fait un resource à stocker dans la db.

**Comment by ssacard** [comment]
OK, partons sur un contrôleur qui va lire des fichiers statiques HTML, qu'on peut insérer dans un template (header/footer/etc..) ? La route pourrait être "/infos/$page", $page étant le nom du fichier  stocké dans /apps/views/static/$page.html.erb

Au fait j'ai vu que le site était à moitié fait en erb et l'autre en haml... haml est un peu chiant à apprendre, mais moins verbeux. C'est quoi le mieux ?

**Comment by oelmekki** [comment]
Done. 

Tu peux donc créer des pages dans apps/view/static/ (j'ai mis un exemple) et y accéder par /infos/<ta_page> . Si la page n'est pas trouvée, la vue "not found" est rendue.

Pour le layout, ça utilise le layout général de l'app ( app/views/layouts/application.haml), mais on peut faire un layout special pour les pages d'infos, si tu veux.

Et donc, je l'avais déjà dit, mais je le repète pour que ce soit au bon endroit, je ne suis pas fan non plus de haml :) Maintenant, quant à dire ce qui est mieux, je ne m'y avancerai pas : haml à se fans et ses haters. Pour moi, c'est une couche d'abstraction de trop, qui perd les intégrateurs.

**Comment by oelmekki** [comment]
Ah d'ailleurs, quand tu crées des nouveaux templates, tu n'es pas obligé d'utiliser haml. Si tu veux écrire du html classique, plutôt que de terminer le nom du fichier par .html.haml, il suffit de le terminer par .html.erb . 

Évidemment, ça fait un peu "mélangé", mais vu nos discussions, je doute que haml survive à la migration rails-3, anw :)
