### ISSUE TITLE
Me transférer les droits de l'application Facebook

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#30]
Je ne sais plus comment cette appli a été faite, pour notamment lister les informations auxquelles on peut accéder, etc. Tu peux me raffraichir la mémoire ? Je mettrai tout dans la doc.

**Comment by oelmekki** [comment]
Hello,

Je t'ai ajouté sur mon compte facebook, il faut que tu m'ajoutes pour que je puisse te mettre dans l'admin.

**Comment by ssacard** [comment]
Cool, merci.
