### ISSUE TITLE
Merger la branche facebook & facebook_i18n

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#31]
J'ai tiré une branche de facebook, facebook_i18n. J'ai commencé à localiser l'application, peux-tu tout merger dans le master et me raffraichir la mémoire sur les mécanismes de merge, rebase, etc ? 

Merci ! 

Ensuite on peut pousser en prod.

**Comment by oelmekki** [comment]
Hello, pour merger la branche facebook_i18n dans la branche facebook :

git checkout facebook // tu passes dans la branches facebook
git merge facebook_i18n // tu merges le contenu de facebook_i18n dans facebook
git push // tu envoies les modifs

**Comment by ssacard** [comment]
Cool, j'ai mergé Facebook_i18n dans Facebook, et Facebook dans Master. Par contre je n'arrive pas à pousser sur Heroku depuis le master hebergé sur Github. J'ai l'impression qu'il y un repository sur github avec ses propres branches, et que le push depuis le master n'est pas autorisé.... je n'ai pas encore creusé, tu as une idée ?

**Comment by oelmekki** [comment]
Je ne suis pas certain de ce que tu veux dire par "pousser sur Heroku depuis le master hebergé sur Github". En principe, tu pull github dans ton repos local et tu pousses sur heroku :
  git pull origin master
  git push heroku master

Quelle commande tu utilises?

**Comment by ssacard** [comment]
Oui je suis pas familiarisé avec les bons termes :) en théorie ce que tu proposes fonctionne, mais je crois me rappeler qu'il y avait eu un fork fait un ami, qui avait été ensuite poussé sur Heroku (donc Github et Heroku ne sont plus synchro).

Donc si j'utilise les bons termes, Heroku et Github sont 2 origin différents...

En local par contre, je suis synchro avec Github.

Quand je fais  git push heroku master il me dit que je ne peux pas faire de fast-forward.

Peut-être que le plus simple et de tout remettre a 0 sur Heroku, en clonant a partir de Github ?

Désolé si je l'emploi pas les bons termes, j'utilise Git 2 fois par an :)
