### ISSUE TITLE
/Register ne redirige plus vers la home quand Facebook est utilisé

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#32]
/register  : Cliquer sur Facebook Connect. 

Après l'authentification via Facebook, on était redirigé vers la home (/home), mais maintenant rien ne se passe. L'authentification Facebook semble bien marcher quand on regarde les logs, mais la redirection ne se fait plus.

**Comment by oelmekki** [comment]
Fixé.

Ça venait en fait du [commit qui comment le footer](https://github.com/ssacard/mon-dvdclub/commit/d100710aef87ab228043970ca921e89a59c2b87b) . Le piège, c'est que les fichiers d'inclusion js étaient au même niveau d'indentation que le footer. Du coup, ils étaient inclus dans le comment.

Et pour répondre à ce que tu avais dit ailleurs ; moi non plus, je ne suis décidément pas fan de haml :)

**Comment by ssacard** [comment]
Cool, merci !

Le 14 juillet 2011 18:32, oelmekki <
reply@reply.github.com> a
crit :

**Comment by oelmekki** [comment]
PS : j'ai créé une nouvelle app facebook pour le dév en local, elle est associée à l'adresse http://0.0.0.0:3000 (l'adresse standard quand on lance ./script/server )

**Comment by ssacard** [comment]
Nickel, merci
