### ISSUE TITLE
Prod : "Se déconnecter" ne fonctionne pas

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#35]
Seulement en prod, en dev cela marche bien (Firefox 5.0.1)

1/ Créer un compte via Facebook
2/ Se connecter 
3/ Cliquer ensuite sur "Se déconnecter"

=> Rien ne se passe. Le cookie fbs_184393274916546 n'est pas supprimé, et la session reste ouverte. En dev, le cookie est bien supprimé.

**Comment by oelmekki** [comment]
Fixed.

Il y avait [un problème dans la lib facebooker2](https://github.com/mmangino/facebooker2/pull/44), j'ai dû la passer en vendor et la patcher.

En conséquence il faut exécuter:
    bundle install

en local pour mettre à jour les dépendences.

**Comment by ssacard** [comment]
Merci !
