### ISSUE TITLE
La connection avec le user "admin" ne marche pas en prod

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#36]
Marche bien en local, mais pas en prod. 

Dans le fichier project_setup.rake, on initialise la base avec le user "admin@dvdclub.com"  / "password". 

J'arrive bien à me loguer avec ce user en local, mais pas en prod. 

Est-ce que ce fichier est toujours utilisé quand on a fait le premier setup de l'application sur Heroku ? Sinon, peux-tu faire en sorte qu'on est un moyen d'accéder aux pages d'admin (/admin/*) avec un user ? 

Merci !

**Comment by ssacard** [comment]
Ha, et je vois que la liste des catégories et des types de support n'est pas chargée, donc ça confirme que le setup de prod n'a pas été fait. Comment faire pour que ces tables soient de nouveau éxécutées pour le premier déploiement, ou comment les charger une fois un déploiement fait ? 

Merci !

**Comment by ssacard** [comment]
Est-ce qu'il suffirait de faire "heroku rake dvdclub:app:setup" par hasard ? 
=> Quand je lance cette ligne de commande, Heroku me dit "Internal Server Error" => Mais rien dans les logs.

**Comment by oelmekki** [comment]
Hello, sorry j'étais sorti chercher du tabac.

Oui effectivement, la base de donnée a été remise à zéro, il faut donc lancer cette tâche pour reseeder la db. Je regarde pourquoi ça ne marche pas.

**Comment by ssacard** [comment]
Ok attention de ne pas faire un reset complet, il y a déjà des users enregistrés !

**Comment by oelmekki** [comment]
Oups, désolé, je viens de le faire :s

Problème fixé, sinon. Je n'avais pas vraiment le temps de regarder pourquoi la tâche ne s'executait pas (d'autant plus que heroku ne donne aucune piste), alors j'ai executé le code de la tache en console.

**Comment by ssacard** [comment]
Pas de problème, tout est à jour les enregistrements n'ont pas été effacés ! Merci

**Comment by oelmekki** [comment]
ouf. J'avais lancé heroku rake app:reset, ça échouait, mais je pensais que c'était au moment où ça appelait la tâche setup. "Heureusement", toutes les tâches custom ont l'air d'échouer.
