### ISSUE TITLE
update dvd_clubs page

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#5]
http://screencast.com/t/ZjEwYzM3ZTIt
- update CSS to remove left column
- remove the "all members" list
- add a link to a page showing all the members
- create the page showing all the members of a club

**Comment by stanguy** [comment]
Would it be ok to apply the same layout to the other pages and not just dvd_clubs? (this is the same everywhere dvd are listed)

There's no left column per se, but the content is right aligned as a float and has a fixed width (hence the 300px gap on the left). This could be modified to be either left aligned or centered:

http://flickr.com/gp/stanguy/391G68
http://flickr.com/gp/stanguy/iCj3v2

**Comment by ssacard** [comment]
Yes, OK. We can have the same layout.

**Comment by ssacard** [comment]
OK, checked.
